In [1]:
import pandas as pd 

path = "C:\\Users\\nagin\\Downloads\\azspeech_sentences.csv"
df = pd.read_csv(path)
df

                                                Sentences
0       Yeddi kilsə monastır kompleksi Qax rayonunun L...
1       Məhz bununla əlaqədar olaraq bu ərazi qədim dö...
2       Kompleksdə eramızın əvvəllərinə aid doqquz abi...
3       Kompleks 1980-ci ildən sonra baxımsızlıqdan sü...
4       Məbədin tarixiylə bağlı kifayət qədər məlumat ...
...                                                   ...
296761                                Elə mən də sevirəm.
296762              Kaş indi bir az olaydı,  çeynəyəydik.
296763                                  Məndə bir az var.
296764        Verim çeynəyin, ancaq sonar özümə qaytarın.
296765  Tom razı oldu, onlar kefiköklükdən ayaqlarını ...

[296766 rows x 1 columns]

In [2]:
from tqdm import tqdm

all_words = []
sentences = df['Sentences'].values.tolist()

for sentence in tqdm(sentences, desc="COUNTING"):
    all_words.extend(sentence.split())

COUNTING: 100%|██████████| 296766/296766 [00:01<00:00, 196626.08it/s]

In [4]:
print(len(set(all_words)))

441070

In [31]:
import pandas as pd

df = pd.read_parquet("C:\\Users\\nagin\\Downloads\\toxic.parquet")
df.sample(1)

,comment,identity_attack,insult,obscene,severe_toxicity,sexual_explicit,threat,toxicity
63983,Bunlara şerefsiz Fransa hansı silahı verdi?dey...,0.0,1.0,1.0,0.0,0.0,0.0,1.0

In [34]:
from flair.data import Corpus
from flair.datasets import ColumnCorpus

corpus: Corpus = ColumnCorpus(
                "resources/tasks/onto-ner",
                column_format={0: "text", 1: "pos", 2: "upos", 3: "ner"},
                tag_to_bioes="ner",
            )

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'resources\\tasks\\onto-ner'

In [ ]:
corpus